/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreelancerRouteImport } from './routes/freelancer'
import { Route as ForFreelancersRouteImport } from './routes/for-freelancers'
import { Route as ForCompaniesRouteImport } from './routes/for-companies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreelancerIndexRouteImport } from './routes/freelancer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FreelancerTimesheetsRouteImport } from './routes/freelancer.timesheets'
import { Route as FreelancerProfileRouteImport } from './routes/freelancer.profile'
import { Route as FreelancerOnboardingRouteImport } from './routes/freelancer.onboarding'
import { Route as FreelancerJobsRouteImport } from './routes/freelancer.jobs'
import { Route as FreelancerEarningsRouteImport } from './routes/freelancer.earnings'
import { Route as FreelancerContractsRouteImport } from './routes/freelancer.contracts'
import { Route as FreelancerApplicationsRouteImport } from './routes/freelancer.applications'
import { Route as AdminTimesheetsRouteImport } from './routes/admin.timesheets'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminFreelancersRouteImport } from './routes/admin.freelancers'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin.jobs.$jobId'
import { Route as AdminFreelancersIdRouteImport } from './routes/admin.freelancers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerRoute = FreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForFreelancersRoute = ForFreelancersRouteImport.update({
  id: '/for-freelancers',
  path: '/for-freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCompaniesRoute = ForCompaniesRouteImport.update({
  id: '/for-companies',
  path: '/for-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerIndexRoute = FreelancerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelancerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FreelancerTimesheetsRoute = FreelancerTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerProfileRoute = FreelancerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerOnboardingRoute = FreelancerOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerJobsRoute = FreelancerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerEarningsRoute = FreelancerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerContractsRoute = FreelancerContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerApplicationsRoute = FreelancerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => FreelancerRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFreelancersRoute = AdminFreelancersRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AdminJobsRoute,
} as any)
const AdminFreelancersIdRoute = AdminFreelancersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFreelancersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-freelancers': typeof ForFreelancersRoute
  '/freelancer': typeof FreelancerRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/freelancers': typeof AdminFreelancersRouteWithChildren
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/freelancer/applications': typeof FreelancerApplicationsRoute
  '/freelancer/contracts': typeof FreelancerContractsRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/jobs': typeof FreelancerJobsRoute
  '/freelancer/onboarding': typeof FreelancerOnboardingRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/timesheets': typeof FreelancerTimesheetsRoute
  '/admin/': typeof AdminIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/admin/freelancers/$id': typeof AdminFreelancersIdRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-freelancers': typeof ForFreelancersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/freelancers': typeof AdminFreelancersRouteWithChildren
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/freelancer/applications': typeof FreelancerApplicationsRoute
  '/freelancer/contracts': typeof FreelancerContractsRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/jobs': typeof FreelancerJobsRoute
  '/freelancer/onboarding': typeof FreelancerOnboardingRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/timesheets': typeof FreelancerTimesheetsRoute
  '/admin': typeof AdminIndexRoute
  '/freelancer': typeof FreelancerIndexRoute
  '/admin/freelancers/$id': typeof AdminFreelancersIdRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/for-companies': typeof ForCompaniesRoute
  '/for-freelancers': typeof ForFreelancersRoute
  '/freelancer': typeof FreelancerRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/freelancers': typeof AdminFreelancersRouteWithChildren
  '/admin/jobs': typeof AdminJobsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/freelancer/applications': typeof FreelancerApplicationsRoute
  '/freelancer/contracts': typeof FreelancerContractsRoute
  '/freelancer/earnings': typeof FreelancerEarningsRoute
  '/freelancer/jobs': typeof FreelancerJobsRoute
  '/freelancer/onboarding': typeof FreelancerOnboardingRoute
  '/freelancer/profile': typeof FreelancerProfileRoute
  '/freelancer/timesheets': typeof FreelancerTimesheetsRoute
  '/admin/': typeof AdminIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/admin/freelancers/$id': typeof AdminFreelancersIdRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/for-companies'
    | '/for-freelancers'
    | '/freelancer'
    | '/how-it-works'
    | '/industries'
    | '/login'
    | '/pricing'
    | '/register'
    | '/sitemap.xml'
    | '/admin/applications'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/freelancers'
    | '/admin/jobs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/timesheets'
    | '/freelancer/applications'
    | '/freelancer/contracts'
    | '/freelancer/earnings'
    | '/freelancer/jobs'
    | '/freelancer/onboarding'
    | '/freelancer/profile'
    | '/freelancer/timesheets'
    | '/admin/'
    | '/freelancer/'
    | '/admin/freelancers/$id'
    | '/admin/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/for-companies'
    | '/for-freelancers'
    | '/how-it-works'
    | '/industries'
    | '/login'
    | '/pricing'
    | '/register'
    | '/sitemap.xml'
    | '/admin/applications'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/freelancers'
    | '/admin/jobs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/timesheets'
    | '/freelancer/applications'
    | '/freelancer/contracts'
    | '/freelancer/earnings'
    | '/freelancer/jobs'
    | '/freelancer/onboarding'
    | '/freelancer/profile'
    | '/freelancer/timesheets'
    | '/admin'
    | '/freelancer'
    | '/admin/freelancers/$id'
    | '/admin/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/for-companies'
    | '/for-freelancers'
    | '/freelancer'
    | '/how-it-works'
    | '/industries'
    | '/login'
    | '/pricing'
    | '/register'
    | '/sitemap.xml'
    | '/admin/applications'
    | '/admin/companies'
    | '/admin/contracts'
    | '/admin/freelancers'
    | '/admin/jobs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/timesheets'
    | '/freelancer/applications'
    | '/freelancer/contracts'
    | '/freelancer/earnings'
    | '/freelancer/jobs'
    | '/freelancer/onboarding'
    | '/freelancer/profile'
    | '/freelancer/timesheets'
    | '/admin/'
    | '/freelancer/'
    | '/admin/freelancers/$id'
    | '/admin/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForCompaniesRoute: typeof ForCompaniesRoute
  ForFreelancersRoute: typeof ForFreelancersRoute
  FreelancerRoute: typeof FreelancerRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer': {
      id: '/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof FreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-freelancers': {
      id: '/for-freelancers'
      path: '/for-freelancers'
      fullPath: '/for-freelancers'
      preLoaderRoute: typeof ForFreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-companies': {
      id: '/for-companies'
      path: '/for-companies'
      fullPath: '/for-companies'
      preLoaderRoute: typeof ForCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/': {
      id: '/freelancer/'
      path: '/'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof FreelancerIndexRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/freelancer/timesheets': {
      id: '/freelancer/timesheets'
      path: '/timesheets'
      fullPath: '/freelancer/timesheets'
      preLoaderRoute: typeof FreelancerTimesheetsRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/profile': {
      id: '/freelancer/profile'
      path: '/profile'
      fullPath: '/freelancer/profile'
      preLoaderRoute: typeof FreelancerProfileRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/onboarding': {
      id: '/freelancer/onboarding'
      path: '/onboarding'
      fullPath: '/freelancer/onboarding'
      preLoaderRoute: typeof FreelancerOnboardingRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/jobs': {
      id: '/freelancer/jobs'
      path: '/jobs'
      fullPath: '/freelancer/jobs'
      preLoaderRoute: typeof FreelancerJobsRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/earnings': {
      id: '/freelancer/earnings'
      path: '/earnings'
      fullPath: '/freelancer/earnings'
      preLoaderRoute: typeof FreelancerEarningsRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/contracts': {
      id: '/freelancer/contracts'
      path: '/contracts'
      fullPath: '/freelancer/contracts'
      preLoaderRoute: typeof FreelancerContractsRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/applications': {
      id: '/freelancer/applications'
      path: '/applications'
      fullPath: '/freelancer/applications'
      preLoaderRoute: typeof FreelancerApplicationsRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/freelancers': {
      id: '/admin/freelancers'
      path: '/freelancers'
      fullPath: '/admin/freelancers'
      preLoaderRoute: typeof AdminFreelancersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof AdminJobsRoute
    }
    '/admin/freelancers/$id': {
      id: '/admin/freelancers/$id'
      path: '/$id'
      fullPath: '/admin/freelancers/$id'
      preLoaderRoute: typeof AdminFreelancersIdRouteImport
      parentRoute: typeof AdminFreelancersRoute
    }
  }
}

interface AdminFreelancersRouteChildren {
  AdminFreelancersIdRoute: typeof AdminFreelancersIdRoute
}

const AdminFreelancersRouteChildren: AdminFreelancersRouteChildren = {
  AdminFreelancersIdRoute: AdminFreelancersIdRoute,
}

const AdminFreelancersRouteWithChildren =
  AdminFreelancersRoute._addFileChildren(AdminFreelancersRouteChildren)

interface AdminJobsRouteChildren {
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
}

const AdminJobsRouteChildren: AdminJobsRouteChildren = {
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
}

const AdminJobsRouteWithChildren = AdminJobsRoute._addFileChildren(
  AdminJobsRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminFreelancersRoute: typeof AdminFreelancersRouteWithChildren
  AdminJobsRoute: typeof AdminJobsRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminFreelancersRoute: AdminFreelancersRouteWithChildren,
  AdminJobsRoute: AdminJobsRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTimesheetsRoute: AdminTimesheetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FreelancerRouteChildren {
  FreelancerApplicationsRoute: typeof FreelancerApplicationsRoute
  FreelancerContractsRoute: typeof FreelancerContractsRoute
  FreelancerEarningsRoute: typeof FreelancerEarningsRoute
  FreelancerJobsRoute: typeof FreelancerJobsRoute
  FreelancerOnboardingRoute: typeof FreelancerOnboardingRoute
  FreelancerProfileRoute: typeof FreelancerProfileRoute
  FreelancerTimesheetsRoute: typeof FreelancerTimesheetsRoute
  FreelancerIndexRoute: typeof FreelancerIndexRoute
}

const FreelancerRouteChildren: FreelancerRouteChildren = {
  FreelancerApplicationsRoute: FreelancerApplicationsRoute,
  FreelancerContractsRoute: FreelancerContractsRoute,
  FreelancerEarningsRoute: FreelancerEarningsRoute,
  FreelancerJobsRoute: FreelancerJobsRoute,
  FreelancerOnboardingRoute: FreelancerOnboardingRoute,
  FreelancerProfileRoute: FreelancerProfileRoute,
  FreelancerTimesheetsRoute: FreelancerTimesheetsRoute,
  FreelancerIndexRoute: FreelancerIndexRoute,
}

const FreelancerRouteWithChildren = FreelancerRoute._addFileChildren(
  FreelancerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ForCompaniesRoute: ForCompaniesRoute,
  ForFreelancersRoute: ForFreelancersRoute,
  FreelancerRoute: FreelancerRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
