// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymwrpxrvfcldtlglncxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltd3JweHJ2ZmNsZHRsZ2xuY3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMwNTc5OTMsImV4cCI6MjA5ODYzMzk5M30.6Cu3IfIvU7WFTqAFn1vqvMzYyGOu8322X1wwAb86JGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});